symfony/src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use ApiPlatform\Core\Annotation\ApiResource;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[ApiResource(
    collectionOperations:["get"],
    itemOperations:[],
)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $name = null;

    #[ORM\Column(nullable: false, options: ['default' => 0])]
    #[Assert\GreaterThanOrEquals(propertyPath:"stock")]
    private ?int $stockage_capacity = null;

    #[ORM\Column(nullable: false, options: ['default' => 0])]
    #[Assert\LessThanOrEquals(propertyPath:"stockage_capacity")]
    private ?int $stock = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $price = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStockageCapacity(): ?int
    {
        return $this->stockage_capacity;
    }

    public function setStockageCapacity(int $stockage_capacity): self
    {
        $this->stockage_capacity = $stockage_capacity;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(?int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }
    
    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }
}

symfony/src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('stockage_capacity')
            ->add('price')
            ->add('stock')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

symfony/src/Controller/ProductController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Entity\Product;
use App\Form\ProductType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;

class ProductController extends AbstractController
{
    /**
     * La page d'accueil affiche la liste des produits
     * @Route("/", name="homepage")
     */
    public function homepage(EntityManagerInterface $entityManager)
    {
        $repository = $entityManager->getRepository(Product::class);
        $products = $repository->findAll();

        return $this->render('product/homepage.html.twig', [
            'products' => $products
        ]);
    }

    /**
     * @Route("/create", name="create")
     * @Route("/update/{id}", name="update")
     */
    public function createOrUpdate(?Product $product, Request $request, EntityManagerInterface $entityManager)
    {
        //Si aucun produit n'est passé à la fonction, c'est une création
        if(!$product){
        $product = new Product;
        }

        $form = $this->createForm(ProductType::class, $product);

        $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()){
                //Pas besoin de persister pour les produits existants
                if(!$product->getId()){
                    $entityManager->persist($product);
                }
                $entityManager->flush();
                return $this->redirectToRoute('homepage');
            }

        return $this->render('product/createupdate.html.twig', [
            'form' => $form->createView(),
            'product' => $product,
        ]);
    }

    /**
     * Suppression par id
     * @Route("/delete/{id}", name="delete")
     */
    public function delete(?Product $product, Request $request, EntityManagerInterface $entityManager)
    {
        $entityManager->remove($product);
        $entityManager->flush();
        $entityManager->flush();
        return $this->redirectToRoute('homepage');
    }

}

symfony/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Bienvenue{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
            <link rel="stylesheet" href="/css/style.css">
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-light bg-light" style="height: 100px;">
          <a href="{{ path('homepage') }}" class="btn btn-primary btn-lg" role="button">
            Liste des produits
          </a>
          <a href="{{ path('create') }}" class="btn btn-primary btn-lg" role="button">
            Nouveau produit
          </a>
        </nav>

        {% block body %}{% endblock %}
    </body>

    <footer class="mt-5 p-3 text-center">
            By Agathe Omnes
    </footer>
</html>

symfony/templates/product/createupdate.html.twig
{% extends 'base.html.twig' %}
 
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-12">
            {% if product.name is empty %}
                <h2 class="my-4">Créer un produit</h2>
            {% else %}
                <h2 class="my-4">Modifier un produit</h2>
            {% endif %}
            <div style="box-shadow: 2px 3px 9px 4px rgba(0,0,0,0.04);">
                <div class="p-container-show p-4">
                    <div class="row">
                        <div class="col">
                            <div class="p-display p-3">
                                {{ form_start(form) }}
                                    <p>
                                        {{ form_label(form.name, 'Nom du produit') }}
                                        {{ form_widget(form.name) }}
                                    </p>
    
                                    <p>
                                        {{ form_label(form.price, 'Prix en €') }}
                                        {{ form_widget(form.price) }}
                                    </p>

                                    <p>
                                        {{ form_label(form.stock, 'Stock actuel') }}
                                        {{ form_widget(form.stock) }}
                                    </p>

                                    <p>
                                        {{ form_label(form.stockage_capacity, 'Capacité de stockage') }}
                                        {{ form_widget(form.stockage_capacity) }}
                                    </p>

                                    {{ form_rest(form) }}

                                    <div class="p-actions">
                                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                                    </div>
                                {{ form_end(form) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

symfony/templates/product/homepage.html.twig
{% extends 'base.html.twig' %}
 
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="my-4">Liste des produits</h2>
            {% if products is empty %}
                Il n'y a pas de produit à afficher
            {% else %}
                {% for product in products %}
                <div style="box-shadow: 2px 3px 9px 4px rgba(0,0,0,0.04);">
                    <div class="p-container-show p-4">
                        <div class="row">
                            <div class="col">
                                <h1 class="p-title-show">{{product.name}}</h1>
                                <div class="p-display p-3">
                                    <p class="d-inline">{{product.price}} €</p>
                                    <p class="pt-4"><strong>{{product.stock}} unité(s) / {{product.stockageCapacity}} total</strong></p>
                                </div>
                                <div class="p-actions">
                                    <a href="{{path('update', {id: product.id})}}">modifier</a>
                                    <a href="{{path('delete', {id: product.id})}}">supprimer</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}